name             'opsline-go-app'
maintainer       'Radek Wierzbicki'
maintainer_email 'radek@opsline.com'
license          'All rights reserved'
description      'Installs/Configures opsline-go-app'
long_description 'Installs/Configures opsline-go-app'
version          '0.2.2'

depends 'artifact', '= 1.12.1'
depends 'logrotate'
